# Generated by Django 3.0.2 on 2020-01-17 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10, null=True, verbose_name='Mobile No')),
                ('photo', models.ImageField(upload_to='profile_pics', verbose_name='Photo')),
                ('street', models.CharField(max_length=100, null=True, verbose_name='Street')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Mobile No')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='State')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
