# Generated by Django 3.0.2 on 2020-01-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile No'),
        ),
    ]
