# Generated by Django 3.0.2 on 2020-01-17 19:17

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_userinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='country1',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email_id',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Id'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
