# Generated by Django 3.0.2 on 2020-01-17 19:17

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_auto_20200118_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='country1',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
