# Generated by Django 3.0.2 on 2020-01-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_auto_20200118_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='country1',
            new_name='country_new',
        ),
    ]
