# Generated by Django 3.0.2 on 2020-01-17 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0011_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='country_new',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile No'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_id',
            field=models.EmailField(blank=True, max_length=20, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Mobile No'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street'),
        ),
    ]
