# Generated by Django 3.0.2 on 2020-01-17 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0012_auto_20200118_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Mobile No'),
        ),
    ]
